### PR TITLE
Use releash for release management

### PR DESCRIPTION
**Pull request by maartenbreddels**
To install:
```bash
pip install releash
```

Workflow:
```bash
$ releash status
# see status, should be all green
# make changes, commit
$ releash status
# will hint to bump version number
$ releash bump --what=patch
# this will bump the version number, and commit the changes
$ releash release
# will tag (annotated), push changes, download the tarball
# and update the recipe in ../xtl-feedstock
```

### CODE REVIEW

**Comment by JohanMabille** [comment]
Here is the output I have when running ``releash status``

```bash
$ releash status
The syntax of the command is incorrect.
The syntax of the command is incorrect.
xtl:            dirty (commit changes)|version not tagged, run release?|1 untracked files
```

Alo it adds __pycache__ to the modified files, so maybe you should add it to the .gitignore

**Comment by maartenbreddels** [comment]
`releash status -v` should print out the command, can you share that?

**Comment by maartenbreddels** [comment]
> Also it adds pycache to the modified files, so maybe you should add it to the .gitignore

In what stage does it do that?

**Comment by JohanMabille** [comment]
Here is the output:

```bash
$ releash status -v
The syntax of the command is incorrect.
The syntax of the command is incorrect.
__pycache__/
xtl:            dirty (commit changes)|version not tagged, run release?|1 untracked files
Untracked files:
git ls-files --other --exclude-standard --directory .
```

The __pycache__ is added the first time I run a releash command, but I don't know a which stage exactly

**Comment by maartenbreddels** [comment]
Ok, that __pycache__ is a python3 features, sorry for that ;)
Can you check if you can run the following commands:
```
$ git ls-files --other --exclude-standard --directory .
$ git ls-files --other --exclude-standard --directory . | wc -l
```
What are you using as a shell (I assume you're on windows)?

**Comment by JohanMabille** [comment]
Here are the outputs:
```bash
$ git ls-files --other --exclude-standard --directory .
__pycache__/
```

And as expected:
```bash
$ git ls-files --other --exclude-standard --directory . | wc -l
1
```

Indeed I'm on windows, using git-bash

**Comment by maartenbreddels** [comment]
Ok, can you upgrade:
```bash
$ pip install --upgrade releash
```
Verbose mode should give more output now.
Do you know of things that git-bash does differently, like can you redirect to stderr using
```bash
$ echo 'bla' &> /dev/null
```
Or does it not like triple dots, like:
```bash
git diff --exit-code v0.1.3...HEAD .
```

**Comment by JohanMabille** [comment]
Here is the output after an upgrade:
```bash
$ releash status -v
The syntax of the command is incorrect.
The syntax of the command is incorrect.
__pycache__/
git diff --exit-code .
git rev-parse 0.2.8
xtl:            dirty (commit changes)|version not tagged, run release?|1 untracked files
Untracked files:
git ls-files --other --exclude-standard --directory .
```

About git-bash differences with bash, I don't know. Redirecting output and triple dots seem to work.

**Comment by maartenbreddels** [comment]
Ok, even when using bash, os.system(..) uses the normal windows shell (makes sense). So I had to change the redirect from stdout and stderr to nul, and windows doesn't understand `;` to execute multiple commands, but '&' works. 0.1.4 fixes this all.

**Pull request merged**
