### PR TITLE
Implement mime_bundle_repr for xoptional, xcomplex and xfixed_string

### PR DESCRIPTION
**Pull request by martinRenou**

### CODE REVIEW

**Comment by SylvainCorlay** [comment]
This looks good to me. However, `nlohmann_json` is an optional dependency of `xtl`.

If you just don't include `nlohmann/json.hpp`, and don't use these functions, they will not be compiled so it should work. Calling them would require adding the include statement.

**Comment by martinRenou** [comment]
I removed the includes like you wanted, but after this change the C++ kernel cannot start anymore... I'm not sure I understand why

**Comment by SylvainCorlay** [comment]
You can troubleshoot it by disabling the redirection of streams and see what gets printed in the console.

**Comment by martinRenou** [comment]
How do I do that ?

**Comment by SylvainCorlay** [comment]
At the moment, that would only be by commenting out `redirect_output`. Maybe we should allow users to set up an environment variable like `XCPP_DISABLE_REDIRECTION` for debug runs.

https://github.com/QuantStack/xeus-cling/blob/master/src/xinterpreter.cpp#L49

**Comment by martinRenou** [comment]
Thank you! Yeah it would be a nice feature

**Comment by martinRenou** [comment]
So if I remove the include, it complains about not finding `nlohmann_json`. There is an include of `xtl/xbasic_fixed_string.hpp` in `xeus/xguid.hpp` which leads to this compilation error. So maybe we should include `nlohmann_json` here.

**Comment by martinRenou** [comment]
Or maybe I could include `nlohmann_json` just after the `#ifdef __CLING__` ?

**Comment by SylvainCorlay** [comment]
Annoying cyclic include...

**Comment by martinRenou** [comment]
As discussed, I've put the include inside of an `#ifdef __CLING__` :)

**Comment by SylvainCorlay** [comment]
LGTM

**Pull request merged**
